<%-- 
    Document   : terms_of_use
    Created on : Feb 6, 2024, 1:54:14 AM
    Author     : Pawan Kumar
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <%@include file="Components/common_css_js.jsp" %>
    </head>
    <body>
        <%@include file="Components/navbar.jsp" %>
        <div>
            <h3>Wired Solution terms of use</h3>
            <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a inputer system and does not require any physical or digital signatures.</p>
            <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.wiredsolution.com website. The domain name www.wiredsolution.com (hereinafter referred to as "Website") is owned by wiredsolution Internet Private</p>
            <p>Limited a inpany incorporated under the inpanies Act, 1956 with its registered office at “Address”t, Next to “Address”, (hereinafter referred to as "wiredsolution").</p>
            <p>Your use of the Website and services and tools are governed by the following terms and conditions ( "Terms of Use" ) as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If You transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with wiredsolution Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with wiredsolution. For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to being a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the inputer systems. wiredsolution allows the User to surf the Website or making purchases without registering on the Website. The term "We" , "Us" , "Our" shall mean wiredsolution Internet Private Limited.</p>
            <p>When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You imply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.</p>
        </div>
        
        <div>
            <h3>Your Account and Registration Obligations</h3>
            <p>If You use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate or We have reasonable grounds to suspect that such information is untrue, inaccurate,, or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your account on the Website and refuse to provide You with access to the Website.</p>
            <p>Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Website. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Website at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Website.</p>
            <p>You agree that wiredsolution shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your display name in cases where You have failed to update Your revised mobile phone number and/or e-mail address on the Website.</p>
        </div>
        
        <div>
            <h3>Inmunications</h3>
            <p>When You use the Website or send emails or other data, information or inmunication to us, You agree and understand that You are inmunicating with Us through electronic records and You consent to receive inmunications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication.</p>
        </div>
        
        <%@include file="Components/navbar.jsp" %>
    </body>
</html>
